[test-groups.ssh-integration]
max-threads = 4

[profile.ci]
fail-fast = false
retries = 4
slow-timeout = { period = "60s", terminate-after = 3 }
status-level = "fail"
final-status-level = "fail"

[[profile.ci.overrides]]
filter = 'binary_id(distant-ssh::lib)'
test-group = 'ssh-integration'
